// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfi9zw6nSAxmTqBO9gOJpBMA3obd6lkIo',
    appId: '1:487292528134:web:c4831245887e0ff2988587',
    messagingSenderId: '487292528134',
    projectId: 'newproject-c2800',
    authDomain: 'newproject-c2800.firebaseapp.com',
    storageBucket: 'newproject-c2800.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfwO0qqE8Q8WFIh01Sqc9cRUpy_9LhghM',
    appId: '1:487292528134:android:c1eaaec03c51f7f9988587',
    messagingSenderId: '487292528134',
    projectId: 'newproject-c2800',
    storageBucket: 'newproject-c2800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclGpFvduXK850YfZIP0w96HfGELm85rc',
    appId: '1:487292528134:ios:af8787623c119f4b988587',
    messagingSenderId: '487292528134',
    projectId: 'newproject-c2800',
    storageBucket: 'newproject-c2800.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDclGpFvduXK850YfZIP0w96HfGELm85rc',
    appId: '1:487292528134:ios:af8787623c119f4b988587',
    messagingSenderId: '487292528134',
    projectId: 'newproject-c2800',
    storageBucket: 'newproject-c2800.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfi9zw6nSAxmTqBO9gOJpBMA3obd6lkIo',
    appId: '1:487292528134:web:1bf77efc707c28b6988587',
    messagingSenderId: '487292528134',
    projectId: 'newproject-c2800',
    authDomain: 'newproject-c2800.firebaseapp.com',
    storageBucket: 'newproject-c2800.firebasestorage.app',
  );

}